language: php

cache:
  directories:
    - vendor

matrix:
  include:
    - php: 8.0
      env: LATEST=YES

install:
  - composer install --no-suggest

script:
  - composer lint
  - composer coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
